In [56]:
import tensorflow as tf
import numpy as np

In [2]:
# initializing tensors

In [3]:
var = tf.Variable("hello hi, how are you", tf.string)

In [5]:
var

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'hello hi, how are you'>

In [6]:
var =tf.constant([20,51,8,4,6,8,1,4,666,1,51,7,56,69])

In [8]:
var.shape

TensorShape([14])

In [9]:
var =tf.constant([20,51,8,4,6,8,1,4,666,1,51,7,56,69], shape=(7,2))

In [10]:
var

<tf.Tensor: shape=(7, 2), dtype=int32, numpy=
array([[ 20,  51],
       [  8,   4],
       [  6,   8],
       [  1,   4],
       [666,   1],
       [ 51,   7],
       [ 56,  69]], dtype=int32)>

In [13]:
# Visualizing variables in model

In [16]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])

In [18]:
model.variables

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[-0.5968791]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [19]:
vector = tf.Variable(initial_value = [1,2])

In [21]:
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [24]:
vector = tf.Variable(initial_value = [1,2,3,4], dtype = tf.float32)

In [25]:
vector

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [37]:
vector1 = tf.Variable([1,2,3,4], shape=tf.TensorShape(None))

In [39]:
vector1

<tf.Variable 'Variable:0' shape=<unknown> dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [41]:
its_complicated = tf.Variable(4 + 3j, dtype=tf.complex64)

In [42]:
its_complicated

<tf.Variable 'Variable:0' shape=() dtype=complex64, numpy=(4+3j)>

In [43]:
# it doen not work
# vector1 = tf.Variable([1,2,3,4], shape=tf.TensorShape(2,2))

In [44]:
tensor = tf.constant([1,2,3,4,5,6,7,8])
tensor

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [45]:
tensor = tf.constant([1,2,3,4,5,6,7,8], shape=(2,4))
tensor

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [46]:
tensor = tf.constant(12, shape=[8,2])
tensor

<tf.Tensor: shape=(8, 2), dtype=int32, numpy=
array([[12, 12],
       [12, 12],
       [12, 12],
       [12, 12],
       [12, 12],
       [12, 12],
       [12, 12],
       [12, 12]], dtype=int32)>

In [49]:
tf.add([1,2], [3,4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [50]:
tf.square(5)

<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [52]:
tf.reduce_sum([[151,15],[95,75]])

<tf.Tensor: shape=(), dtype=int32, numpy=336>

In [53]:
tf.reduce_sum([151,15,95,75])

<tf.Tensor: shape=(), dtype=int32, numpy=336>

In [54]:
tf.square(5)+tf.square(2)

<tf.Tensor: shape=(), dtype=int32, numpy=29>

In [57]:
# Create a 1D uint8 NumPy array comprising of first 25 natural numbers
x = np.arange(0, 25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
# Convert NumPy array to Tensor using `tf.constant`
x = tf.constant(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

In [ ]:
x = tf.cast(x, tf.float32)
x

In [59]:
try:
    # This will produce a ValueError
    tf.Variable([1,2,3,4], shape=(2,2))
except ValueError as v:
    # See what the ValueError says
    print(v)

The initial value's shape ((4,)) is not compatible with the explicitly supplied `shape` argument ((2, 2)).
